version: '3'
services:
  socket-server:
    build:
      context: ./
      dockerfile: Dockerfile-socket-server
    volumes:
       - "/Users/miksto/www:/home/app/files/"
    ports:
      - "3000:3000"
  file-server:
    build:
      context: ./
      dockerfile: Dockerfile-file-server
    volumes:
       - "/Users/miksto/www:/home/app/files/"
    ports:
      - "8080:8080"

