FROM python:3.6-stretch

# Create app directory
WORKDIR /home/app

RUN pip install obspy
RUN pip install matplotlib
RUN pip install websockets

# Bundle app source
COPY python-server.py ./
COPY stream_plotter.py ./

CMD [ "python", "python-server.py" ]