FROM python:3.6-stretch

# Create app directory
WORKDIR /home/app

RUN pip install --upgrade pip

RUN pip install pipenv
COPY Pipfile ./
COPY Pipfile.lock ./
RUN pipenv install --deploy --ignore-pipfile

# Bundle app source
COPY python-server.py ./
COPY stream_plotter.py ./
COPY stream_manager.py ./
COPY seismometer.py ./

CMD ["pipenv", "run", "python", "-u", "python-server.py" ]
