version: '3'
services:
  socket-server:
    build:
      context: ./
      dockerfile: Dockerfile-socket-server
    volumes:
       - "/Users/miksto/www:/home/app/files/"
    ports:
      - "3000"
    env_file:
      - .env
  
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    volumes:
       - "/Users/miksto/www/:/usr/share/nginx/html/"
    ports:
      - "80:80"

