version: '3'
services:
  socket-server:
    build:
      context: ./
      dockerfile: Dockerfile-socket-server
    volumes:
      - "./files:/home/app/files/"
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: on-failure
