FROM python:3.6-stretch

# Create app directory
WORKDIR /home/app

RUN pip install --upgrade pip
RUN pip install numpy
RUN pip install obspy
RUN pip install matplotlib
RUN pip install websockets

# Bundle app source
COPY python-server.py ./
COPY stream_plotter.py ./
COPY stream_manager.py ./

CMD [ "python", "-u", "python-server.py" ]
